import { useEffect } from 'react';
import { Vibration } from 'react-native';
import { setAudioModeAsync, useAudioPlayer } from 'expo-audio';

/** Buzz pattern for the vibration alarm: long-short-long-short, repeating. */
const VIBRATION_PATTERN = [0, 600, 400, 600, 400];

/**
 * The audible + haptic alarm that runs during the "Are you OK?" countdown.
 *
 * `assets/siren.wav` is a 2 s two-tone sweep generated by
 * `scripts/make-siren.js`, looped for as long as the alarm is active.
 *
 * Both channels are independent so the user can have a silent-but-buzzing
 * alarm (a meeting) or an audible-but-still one — see Settings → Alerts.
 */
export function useAlarm({
  active,
  sound,
  vibrate,
}: {
  /** Runs the alarm while true; stops and cleans up when false. */
  active: boolean;
  sound: boolean;
  vibrate: boolean;
}) {
  const player = useAudioPlayer(require('../../assets/siren.wav'));

  useEffect(() => {
    if (!active) return;

    if (vibrate) Vibration.vibrate(VIBRATION_PATTERN, true);
    else Vibration.vibrate(400); // one confirmation buzz even when muted

    if (sound) {
      // An emergency alarm should be heard over a silent switch and should
      // interrupt whatever else is playing, not politely duck under it.
      setAudioModeAsync({
        playsInSilentMode: true,
        interruptionMode: 'doNotMix',
        shouldPlayInBackground: false,
      }).catch(() => undefined);

      try {
        player.loop = true;
        player.volume = 1;
        player.seekTo(0).catch(() => undefined);
        player.play();
      } catch {
        // A dead player must never take the countdown down with it.
      }
    }

    return () => {
      Vibration.cancel();
      try {
        player.pause();
      } catch {
        // Player already released by the hook's own teardown.
      }
    };
  }, [active, sound, vibrate, player]);
}
